name: qrcode_example
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  gallery_saver: ^2.3.2
  hive_flutter: ^1.1.0
  hooks_riverpod: ^1.0.3
  path_provider: ^2.0.9
  permission_handler: ^9.1.0
  qr_code_scanner: ^0.7.0
  qr_flutter: ^4.0.0
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
